<?php echo "<?php\n"; ?>
/**
 * AUTOGENERATED ONLY IF ABSENT
 * Edit this file to match your needs
 * To reset from defaults, run `composer horde:reconfigure --force --mode=<?= $mode ?>`
 */
$deployment_webroot = '<?= $webrootUri ?>';
$app_fileroot = '<?= $appFileroot ?>';
$app_webroot = '<?= $appWebroot ?>';
