<?php echo "<?php\n"; ?>
/**
 * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH
 * composer horde-reconfigure or install/update
 * Override settings in either:
 * - var/config/horde/registry.local.php
 * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php
 * - var/config/horde/registry-sub.domain.org.php
 */
$this->applications['horde']['fileroot'] = '<?= $appInVendorDir ?>';
$this->applications['horde']['templates'] = '<?= $appInVendorDir ?>templates<?= $ds ?>';
$this->applications['horde']['webroot'] = '<?= $webrootUri ?>horde/';
$this->applications['horde']['jsfs'] = '<?= $webDir . $ds ?>js<?= $ds ?>horde<?= $ds ?>';
$this->applications['horde']['jsuri'] = '<?= $webrootUri ?>js/horde';
$this->applications['horde']['staticfs'] = '<?= $webDir . $ds ?>static<?= $ds ?>';
$this->applications['horde']['staticuri'] = '<?= $webrootUri ?>static/';
$this->applications['horde']['themesfs'] = '<?= $webDir . $ds ?>themes<?= $ds ?>horde<?= $ds ?>';
$this->applications['horde']['themesuri'] = '<?= $webrootUri ?>themes/horde';
