<?php echo "<?php\n"; ?>
/**
 * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH
 * composer horde-reconfigure or install/update
 * Override settings in either:
 * - var/config/horde/registry.local.php
 * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php
 * - var/config/horde/registry-sub.domain.org.php
 */
$this->applications['<?= $appName ?>']['fileroot'] = '<?= $appInVendorDir ?>';
$this->applications['<?= $appName ?>']['templates'] = '<?= $appInVendorDir ?>templates<?= $ds ?>';
$this->applications['<?= $appName ?>']['themesfs'] = '<?= $webDir . $ds ?>themes<?= $ds . $appName . $ds ?>';
$this->applications['<?= $appName ?>']['jsfs'] = '<?= $webDir . $ds ?>js<?= $ds . $appName . $ds ?>';
$this->applications['<?= $appName ?>']['webroot'] = '<?= $webrootUri . $appName ?>/';
$this->applications['<?= $appName ?>']['jsuri'] = '<?= $webrootUri ?>js/<?= $appName ?>';
$this->applications['<?= $appName ?>']['themesuri'] = '<?= $webrootUri ?>themes/<?= $appName ?>';
// End of <?= $appName ?> registry snippet
