<?php echo "<?php\n"; ?>
/**
 * AUTOGENERATED ONLY IF ABSENT
 * If you activate at least one of these lines, please also set a full https URL for the default webroot where the remaining apps and the assets (js, themes, static) are located
 * Run `composer horde:reconfigure --mode=<?= $mode ?> --webroot="https://assets.example.com/"`
 */
<?php foreach ($apps as $app):
    [, $appName] = explode('/', $app);
    ?>
// Customize <?= $app ?> webroot
// $this->applications['<?= $appName ?>']['webroot'] = 'https://<?= $appName ?>.example.com/';
<?php endforeach; ?>
