<?= "<?php\n" ?>
declare(strict_types=1);
/**
 * AUTOGENERATED ONLY IF ABSENT.
 * Edit this file to match your needs. If edited, this file is backup relevant.
 * To redo, delete file and run `composer horde-reconfigure`
 */
// Default configuration relative to an autodetected webroot. This works in most cases.
$deployment_webroot = '/';
$deployment_fileroot = '<?= $this->webDir; ?>';
$app_fileroot = '/var/www/horde-dev/web/horde';
$app_webroot = <?php $this->webDir; ?>'/horde';

// Support separate webroots for some or all apps.
// As of horde-installer-plugin 2.7 this is an experimental feature and might be subject to breaking changes.
$canonical_webroots = [];
$useSubdomains = false;

if (isset($useSubdomains) and $useSubdomains) {
// If you use a different webroot for at least one app, you should also set this. 
// Otherwise navigating from one app to another yields unexpected results.
$canonical_webroots = [
    'horde' => 'https://horde.mydomain.com/horde',
    'js' => 'https://horde.mydomain.com/js',
    'static' => 'https://horde.mydomain.com/static',
    'themes' => 'https://horde.mydomain.com/themes',
];

// Example for a custom webroot for an app
// $canonical_webroots['myapp'] = 'http://myapp.dev.localhost:5080/horde';
<?php
$suggestedSubdomains = [
    'nag' => 'tasks',
    'turba' => 'contacts',
    'kronolith' => 'calendar',
    'ansel' => 'photos',
    'wicked' => 'wiki',
    'passwd' => 'password',
    'chora' => 'code',
    'imp' => 'webmail',
    'whups' => 'tickets',
];
$skipApps = [
    'horde/components',
    'horde/horde',
    'horde/base',
];
foreach ($this->apps as $app) {
    // Skip these horde/components app
    if (in_array($app, $skipApps)) {
        continue;
    }
    [$vendor, $name] = explode('/', $app, 2);
    $subdomain = $suggestedSubdomains[$name] ?? $name;
    echo '$canonical_webroots[\'' . $name . "'] = \'https://$subdomain.mydomain.com/';\n";
}
?>

}