<?php

declare(strict_types=1);

namespace Horde\Composer;

use Composer\Command\BaseCommand;
use Composer\Factory as ComposerFactory;
use Composer\Plugin\Capability\CommandProvider as CommandProviderCapability;
use Composer\Package\Dumper\ArrayDumper;
use Composer\Json\JsonFile;
use Composer\Config\JsonConfigSource;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Horde\Composer\IOAdapter\SymphonyOutputAdapter;
use InvalidArgumentException;

class HordeReconfigureCommand extends BaseCommand
{
    protected function configure(): void
    {
        $this->setName('horde:reconfigure')->setAliases(['horde-reconfigure']);
        $this->addOption('mode', 'm', InputOption::VALUE_OPTIONAL, 'Should we "proxy" (default) files from vendor to the webdir? Alternatives: "symlink", "copy"', '');
        $this->addOption('webroot', null, InputOption::VALUE_REQUIRED, 'The default webroot for the /horde, /js, /themes, /static and /$app dirs if not specifically overridden. Use either a relative path or a full HTTPS url. Examples: "/" (default), "/groupware", "http://localhost/", "https://horde.example.com"', '');
        $this->addOption('app', null, InputOption::VALUE_REQUIRED, 'global, horde or app name', 'global');
        $this->addOption('resource', null, InputOption::VALUE_REQUIRED, 'jsuri, themesuri, webroot, staticuri', 'webroot');
        $this->addOption('force', null, InputOption::VALUE_NONE, 'Delete and rewrite items normally left untouched', null);
        $this->setDescription('Rewrite autogenerated configuration');
        $this->setHelp(
            <<<EOT
                Horde Installer writes various symlinks and files with installation specific paths.
                If you move your installation around or manually tinker with local files, you may need to re-run this.
                EOT
        );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // @phpstan-ignore-next-line This is for upgrading. An older version without reconfigure might be installed first.
        if (method_exists($this, 'requireComposer')) {
            $composer = $this->requireComposer();
        } else {
            $composer = $this->getComposer();
        }
        if (!$composer) {
            die('Error: Command was run without a relation to composer itself');
        }
        $mode = (string) $input->getOption('mode');
        $force = (bool) $input->getOption('force');
        $uri = $input->getOption('webroot');
        $app = $input->getOption('app');
        $resource = $input->getOption('resource');
        if (!str_ends_with($uri, '/')) {
            $uri .= '/';
        }
        // Memorize webroot in the composer.json file
        $rootPackage =  $composer->getPackage();
        $extra = $rootPackage->getExtra();
        $dirty = false;
        if ($mode == '') {
            $mode = $extra['horde-reconfigure']['mode'] ?? 'proxy';
        } else  {
            $extra['horde-reconfigure']['mode'] = $mode;
        }
        if ($input->getOption('webroot')) {
            $extra['horde-registry'][$app][$resource] = $uri;
            $dirty = true;
        }
        if ($dirty) {
            $rootPackage->setExtra($extra);
            $file = ComposerFactory::getComposerFile();
            $jsonFile = new JsonFile($file);
            $data = $jsonFile->read();
            $data['extra'] = $extra;
            $jsonFile->write($data);
        }
        $webroot = $extra['horde-registry'][$app][$resource] ?? '/';

        try {
            $reconfigureOptions = new ReconfigureOptions(mode: $mode, force: $force, webroot: $webroot, extra: $extra);
        } catch (InvalidArgumentException $e) {
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            return 1;
        }
        // This is needed to support PHP 7.4 (no union types) for both Composer 2.2 / 2.3
        // Cannot use instanceof here as the class will not exist in 2.2.
        if (get_class($composer) === 'Composer\PartialComposer') {
            $flow = HordeReconfigureFlow::fromPartialComposer($composer, new SymphonyOutputAdapter($output), $reconfigureOptions);
        } else {
            $flow = HordeReconfigureFlow::fromComposer($composer, new SymphonyOutputAdapter($output), $reconfigureOptions);
        }
        return $flow->run();
    }
}
