<?php

declare(strict_types=1);

namespace Horde\Composer;

use Composer\Util\Filesystem;

class RegistrySnippetFileWriter
{
    /**
     * List of apps
     *
     * @var string[]
     */
    private array $apps;
    private string $configDir;
    private string $configRegistryDir;
    private string $webDir;

    /**
     * Undocumented function
     *
     * @param Filesystem $filesystem
     * @param string $baseDir
     * @param string[] $apps
     */
    public function __construct(
        private Filesystem $filesystem,
        /**
         * The config dir for the registry
         */
        private string $baseDir,
        array $apps,
        private ReconfigureOptions $options = new ReconfigureOptions(),
    ) {
        /**
         * The config dir for the registry
         */
        $this->configDir = $baseDir . '/var/config';
        /**
         * The config dir for the registry snippets
         */
        $this->configRegistryDir = $this->configDir . DIRECTORY_SEPARATOR . 'horde' . DIRECTORY_SEPARATOR . 'registry.d';
        $this->webDir = $baseDir . DIRECTORY_SEPARATOR . 'web';
        $this->apps = $apps;
    }

    public function run(): void
    {
        $webrootUri = $this->options->webroot;
        // Ensure we have the base locations right
        $registry00FilePath = $this->configRegistryDir . '/00-horde.php';

        // Check if paths have changed (migration detection)
        $needsRegeneration = false;
        if (file_exists($registry00FilePath)) {
            $existingContent = file_get_contents($registry00FilePath);
            // Check if file contains old base directory path
            if (strpos($existingContent, '$deployment_fileroot') !== false
                && strpos($existingContent, $this->webDir) === false) {
                $needsRegeneration = true;
            }
        }

        if (!file_exists($registry00FilePath) || $needsRegeneration) {
            $registry00FileContent = '<?php' . PHP_EOL
            . '/**' . PHP_EOL
            . ' * AUTOGENERATED ONLY IF ABSENT' . PHP_EOL
            . ' * Edit this file to match your needs' . PHP_EOL
            . ' * To reset from defaults, run `composer horde:reconfigure --force --mode=' . $this->options->mode . '`' . PHP_EOL
            . ' */' . PHP_EOL;
            $registry00FileContent .= sprintf(
                '$deployment_webroot = \'%s\';
$deployment_fileroot = \'%s\';
$app_fileroot = \'%s\';
$app_webroot = \'%s\';
',
                $webrootUri,
                $this->webDir,
                $this->webDir . DIRECTORY_SEPARATOR . 'horde',
                '/horde',
            );
            $this->filesystem->filePutContentsIfModified($registry00FilePath, $registry00FileContent);
        }
        $webrootOverrideFilePath = $this->configDir . '/horde/registry.d/03-override-webroots.php';
        $webrootOverrideFileSnippet = '<?php' . PHP_EOL
        . '/**' . PHP_EOL
        . ' * AUTOGENERATED ONLY IF ABSENT' . PHP_EOL
        . ' * If you activate at least one of these lines, please also set a full https URL for the default webroot where the remaining apps and the assets (js, themes, static) are located' . PHP_EOL
        . ' * Run `composer horde:reconfigure --mode=' . $this->options->mode . ' --webroot="https://assets.example.com/"`' . PHP_EOL
        . ' */' . PHP_EOL;

        // Ensure we have a base
        foreach ($this->apps as $app) {
            [$appVendor, $appName] = explode('/', $app);
            $webrootOverrideFileSnippet .= '// Customize ' . $app . ' webroot' . PHP_EOL;
            $webrootOverrideFileSnippet .= "// \$this->applications['$appName']['webroot'] = 'https://$appName.example.com/';" . PHP_EOL;
            $registryAppSnippet = '<?php' . PHP_EOL
            . '/**' . PHP_EOL
            . ' * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH' . PHP_EOL
            . ' * composer horde-reconfigure or install/update' . PHP_EOL
            . ' * Override settings in either:' . PHP_EOL
            . ' * - var/config/horde/registry.local.php' . PHP_EOL
            . ' * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php' . PHP_EOL
            . ' * - var/config/horde/registry-sub.domain.org.php' . PHP_EOL
            . ' */' . PHP_EOL;

            $appInVendorDir = $this->baseDir . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . $appVendor . DIRECTORY_SEPARATOR . $appName . DIRECTORY_SEPARATOR;
            if ($app == 'horde/horde') {
                $registryAppFilename = $this->configRegistryDir . '/01-location-' . $appName . '.php';
                $registryAppSnippet
                .= '$this->applications[\'' . $appName . '\'][\'fileroot\'] = \'' . $appInVendorDir . '\';' . PHP_EOL
                . '$this->applications[\'' . $appName . '\'][\'templates\'] = \'' . $appInVendorDir . 'templates' . DIRECTORY_SEPARATOR . '\';' . PHP_EOL
                . "\$this->applications['horde']['webroot'] = '{$webrootUri}horde/';" . PHP_EOL
                . '$this->applications[\'horde\'][\'jsfs\'] = $deployment_fileroot . \'/js/horde/\';' . PHP_EOL
                . "\$this->applications['horde']['jsuri'] = '{$webrootUri}js/horde';" . PHP_EOL
                . '$this->applications[\'horde\'][\'staticfs\'] = $deployment_fileroot . \'/static\';' . PHP_EOL
                . "\$this->applications['horde']['staticuri'] = '{$webrootUri}static/';" . PHP_EOL
                . '$this->applications[\'horde\'][\'themesfs\'] = $deployment_fileroot . \'/themes/horde/\';' . PHP_EOL
                . "\$this->applications['horde']['themesuri'] = '{$webrootUri}themes/horde';" . PHP_EOL;
            } else {
                // A registry snippet should ensure the install dir is known
                $registryAppFilename = $this->configRegistryDir . '/02-location-' . $appName . '.php';
                $registryAppSnippet
                .= '$this->applications[\'' . $appName . '\'][\'fileroot\'] = \'' . $appInVendorDir . '\';' . PHP_EOL
                . '$this->applications[\'' . $appName . '\'][\'templates\'] = \'' . $appInVendorDir . 'templates' . DIRECTORY_SEPARATOR . '\';' . PHP_EOL
                . '$this->applications[\'' . $appName . '\'][\'themesfs\'] = \'' . $this->webDir . DIRECTORY_SEPARATOR . 'themes' . DIRECTORY_SEPARATOR . $appName . DIRECTORY_SEPARATOR . '\';' . PHP_EOL
                . '$this->applications[\'' . $appName . '\'][\'jsfs\'] = \'' . $this->webDir . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR . $appName . DIRECTORY_SEPARATOR . '\';' . PHP_EOL
                . "\$this->applications['$appName']['webroot'] = '{$webrootUri}$appName/';" . PHP_EOL
                . "\$this->applications['$appName']['jsuri'] = '{$webrootUri}js/$appName';" . PHP_EOL
                . "\$this->applications['$appName']['themesuri'] = '{$webrootUri}themes/$appName';" . PHP_EOL
                . '// End of ' . $appName . ' registry snippet' . PHP_EOL;
            }
            // Some versions of the middleware router require the routes.php file to exist even if empty
            $routesFilePath = $appInVendorDir . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'routes.php';
            if (is_dir(dirname($routesFilePath)) && !file_exists($routesFilePath)) {
                $this->filesystem->filePutContentsIfModified($routesFilePath, '<?php' . PHP_EOL . '// Empty default routes file. Put custom routes into var/config/' . $appName . '/routes.local.php and run composer horde:reconfigure' . PHP_EOL);
            }
            $this->filesystem->filePutContentsIfModified($registryAppFilename, $registryAppSnippet);
        }
        if (!file_exists($webrootOverrideFilePath)) {
            $this->filesystem->filePutContentsIfModified($webrootOverrideFilePath, $webrootOverrideFileSnippet);
        }
    }
}
